//! `Store` methods for project-level persistence: upsert and fetch.
//!
//! Projects are the top-level scope for all memories. A project row is created
//! (or updated) once per `vestige init` run. The `id` column is stable for the
//! lifetime of a repo; never regenerated by a re-init (PRD §9.3).
//!
//! Timestamps are stored as RFC-3339 strings in UTC — SQLite has no native
//! timestamp type and TEXT is the canonical Vestige convention.

use std::str::FromStr;

use time::OffsetDateTime;

use vestige_core::{ProjectId, ProjectRecord};

use crate::helpers::{invalid_id_to_sqlite, parse_rfc3339, rfc3339};
use crate::{Result, Store, StoreError};

impl Store {
    /// Upsert a project row, returning the current persisted state.
    ///
    /// Uses `INSERT … ON CONFLICT(id) DO UPDATE` so re-running `vestige init`
    /// refreshes `name`, `root_path`, and `git_remote` without rotating the
    /// `project_id` or `created_at`. Idempotent by design (PRD §4.1).
    ///
    /// Side-effect: updates `updated_at` on every call, even when nothing
    /// else changes — acceptable overhead for an init-time operation.
    pub fn ensure_project(
        &mut self,
        id: &ProjectId,
        name: &str,
        root_path: Option<&str>,
        git_remote: Option<&str>,
    ) -> Result<ProjectRecord> {
        let now_str = rfc3339(OffsetDateTime::now_utc())?;

        self.conn.execute(
            "INSERT INTO projects (id, name, root_path, git_remote, created_at, updated_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?5)
             ON CONFLICT(id) DO UPDATE SET
                name = excluded.name,
                root_path = excluded.root_path,
                git_remote = excluded.git_remote,
                updated_at = excluded.updated_at",
            rusqlite::params![id.as_str(), name, root_path, git_remote, now_str],
        )?;

        self.get_project(id)?.ok_or_else(|| {
            StoreError::Corruption(format!("project {id} missing immediately after upsert"))
        })
    }

    /// Fetch a project by ID. Returns `None` if not found.
    pub fn get_project(&self, id: &ProjectId) -> Result<Option<ProjectRecord>> {
        let mut stmt = self.conn.prepare(
            "SELECT id, name, root_path, git_remote, created_at, updated_at
             FROM projects WHERE id = ?1",
        )?;
        let mut rows = stmt.query(rusqlite::params![id.as_str()])?;
        if let Some(row) = rows.next()? {
            Ok(Some(row_to_project(row)?))
        } else {
            Ok(None)
        }
    }
}

/// Map a `projects` SELECT row (columns 0–5) into a [`ProjectRecord`].
fn row_to_project(row: &rusqlite::Row<'_>) -> Result<ProjectRecord> {
    let id_str: String = row.get(0)?;
    let id = ProjectId::from_str(&id_str).map_err(invalid_id_to_sqlite)?;
    let name: String = row.get(1)?;
    let root_path: Option<String> = row.get(2)?;
    let git_remote: Option<String> = row.get(3)?;
    let created_str: String = row.get(4)?;
    let updated_str: String = row.get(5)?;

    Ok(ProjectRecord {
        id,
        name,
        root_path,
        git_remote,
        created_at: parse_rfc3339(&created_str, 4)?,
        updated_at: parse_rfc3339(&updated_str, 5)?,
    })
}
